name: OpenAPI Validate
on:
  pull_request:
    paths: [ "openapi.v1.json" ]
jobs:
  spectral:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: npm i -g @stoplight/spectral-cli
      - run: spectral lint openapi.v1.json
